[package]
name = "cfx-wasm-runtime"
version = "0.1.0"
authors = ["ZOTTCE <zottce@gmail.com>"]
edition = "2018"

[dependencies]
wasmtime = "0.28.0"
wasmtime-wasi = "0.28.0"
cfx-wasm-rt-types = { path = "../rt-types", default-features = false }
anyhow = "1.0"
